### ISSUE TITLE
Missing license data in dist.ini causes dzil to choke

### ISSUE THREAD

**Issue by cxw42** [perlancar/perl-Getopt-Long-Subcommand#2]
After a fresh fork/clone:

    $ (dzil authordeps --missing ; dzil listdeps --missing)
    [DZ] no license data in config, no %Rights stash, couldn't make a good guess at license from Pod; giving up.  Perhaps you need to set up a global config file (dzil setup)?
    [DZ] no license data in config, no %Rights stash, couldn't make a good guess at license from Pod; giving up.  Perhaps you need to set up a global config file (dzil setup)? at inline delegation in Dist::Zilla for logger->log_fatal (attribute declared in /home/cwhite/perl5/lib/perl5/Dist/Zilla.pm at line 768) line 18.

I suspect you have a global config, but I can't build this repo without it, or the equivalent in some form.

**Comment by perlancar** [comment]
Sorry for the late response, didn't see the notification for this issue until today.

I've readded license information in `dist.ini` to make my distros more easily buildable by others.
